# Generated by Django 5.2.1 on 2025-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=150)),
            ],
        ),
    ]
