# Generated by Django 5.2.1 on 2025-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
